---
title: "Synaptic gene expression changes in frontotemporal dementia due to the MAPT 10 + 16 mutation"
date: 2024-8-20
---

_[Published](https://onlinelibrary.wiley.com/doi/full/10.1111/nan.13006) in Neuropathology and Applied Neurobiology_

Mutations in the MAPT gene encoding tau protein can cause autosomal dominant neurodegenerative tauopathies including frontotemporal dementia (often with Parkinsonism). In Alzheimer's disease, the most common tauopathy, synapse loss is the strongest pathological correlate of cognitive decline. Recently, Positron Emission Tomography (PET) imaging with synaptic tracers revealed clinically relevant loss of synapses in primary tauopathies; however, the molecular mechanisms leading to synapse degeneration in primary tauopathies remain largely unknown. In this study, we examined post-mortem brain tissue from people who died with frontotemporal dementia with tau pathology (FTDtau) caused by the MAPT intronic exon 10 + 16 mutation, which increases splice variants containing exon 10 resulting in higher levels of tau with four microtubule-binding domains.

We used RNA sequencing and histopathology to examine temporal cortex and visual cortex, to look for molecular phenotypes compared to age, sex and RNA integrity matched participants who died without neurological disease (n = 12 FTDtau10 + 16 and 13 controls).

Bulk tissue RNA sequencing reveals substantial downregulation of gene expression associated with synaptic function. Upregulated biological pathways in human MAPT 10 + 16 brain included those involved in transcriptional regulation, DNA damage response and neuroinflammation. Histopathology confirmed increased pathological tau accumulation in FTDtau10 + 16 cortex as well as a loss of presynaptic protein staining and region-specific increased colocalization of phospho-tau with synapses in temporal cortex.

Our data indicate that synaptic pathology likely contributes to pathogenesis in FTDtau10 + 16 caused by the MAPT 10 + 16 mutation.

_Recommended citation: Dando O, McGeachan R, McQueen J, et al. Synaptic gene expression changes in frontotemporal dementia due to the MAPT 10 + 16 mutation. Neuropathol Appl Neurobiol. 2024; 50(4):e13006. doi:10.1111/nan.13006_