---
title: 'Cystatin F (Cst7) drives sex-dependent changes in microglia in an amyloid-driven model of Alzheimer’s disease'
date: 2023-12-12
---

_[Published](https://elifesciences.org/articles/85279) in eLife_

Microglial endolysosomal (dys)function is strongly implicated in neurodegenerative disease. Transcriptomic studies show that a microglial state characterised by a set of genes involved in endolysosomal function is induced in both mouse Alzheimer’s disease (AD) models and human AD brain, and that the emergence of this state is emphasised in females. Cst7 (encoding cystatin F) is among the most highly upregulated genes in these microglia. However, despite such striking and robust upregulation, the function of Cst7 in neurodegenerative disease is not understood. 

Here, we crossed Cst7<sup>-/-</sup> mice with the App<sup>NL-G-F</sup> mouse to test the role of Cst7 in a model of amyloid-driven AD. Surprisingly, we found that Cst7 plays a sexually dimorphic role regulating microglia in this model. In females, Cst7<sup>-/-</sup>App<sup>NL-G-F</sup> microglia had greater endolysosomal gene expression, lysosomal burden, and amyloid beta (Aβ) burden in vivo and were more phagocytic in vitro. However, in males, Cst7<sup>-/-</sup>App<sup>NL-G-F</sup> microglia were less inflammatory and had a reduction in lysosomal burden but had no change in Aβ burden. 

Overall, our study reveals functional roles for one of the most commonly upregulated genes in microglia across disease models, and the sex-specific profiles of Cst7<sup>-/-</sup>-altered microglial disease phenotypes. More broadly, the findings raise important implications for AD including crucial questions on sexual dimorphism in neurodegenerative disease and the interplay between endolysosomal and inflammatory pathways in AD pathology.

_Recommended citation: Michael JD Daniels, Lucas Lefevre, Stefan Szymkowiak, Alice Drake, Laura McCulloch, Makis Tzioras, Jack Barrington, Owen R Dando, Xin He, Mehreen Mohammad, Hiroki Sasaguri, Takashi Saito, Takaomi C Saido, Tara L Spires-Jones, Barry W McColl (2023), Cystatin F (Cst7) drives sex-dependent changes in microglia in an amyloid-driven model of Alzheimer’s disease, eLife, 12:e85279_
