project:
  type: website

website:
  title: "Owen Dando"
  site-url: "https://lweasel.github.io"
  repo-url: "https://github.com/lweasel/lweasel.github.io"

  navbar:
    pinned: true

    left:
      - text: "About"
        href: "index.qmd"
      - text: "Blog"
        file: blog/index.qmd
      - text: "Publications"
        file: publications/index.qmd

    right:
      - text: "{{< iconify fa6-brands bluesky size=1.1em title='Bluesky' >}}"
        href: https://bsky.app/profile/owendando.bsky.social
        rel: me
      - text: "{{< iconify bi mastodon size=1.1em title='Mastodon' >}}"
        href: https://mastodon.scot/@odando
        rel: me
      - text: "{{< iconify bi github size=1.1em title='GitHub' >}}"
        href: https://github.com/lweasel
        rel: me
      
  page-footer: | 
    © 2025 Owen Dando. Made with [Quarto](https://quarto.org/).

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



