---
title: "Altered dendritic spine function and integration in a mouse model of fragile X syndrome"
date: 2019-10-23
---

_[Published](https://doi.org/10.1038/s41467-019-11891-6) in Nature Communications_

Cellular and circuit hyperexcitability are core features of fragile X syndrome and related autism spectrum disorder models. However, the cellular and synaptic bases of this hyperexcitability have proved elusive. We report in a mouse model of fragile X syndrome, glutamate uncaging onto individual dendritic spines yields stronger single-spine excitation than wild-type, with more silent spines. Furthermore, fewer spines are required to trigger an action potential with near-simultaneous uncaging at multiple spines. This is, in part, from increased dendritic gain due to increased intrinsic excitability, resulting from reduced hyperpolarization-activated currents, and increased NMDA receptor signaling. Using super-resolution microscopy we detect no change in dendritic spine morphology, indicating no structure-function relationship at this age. However, ultrastructural analysis shows a 3-fold increase in multiply-innervated spines, accounting for the increased single-spine glutamate currents. Thus, loss of FMRP causes abnormal synaptogenesis, leading to large numbers of poly-synaptic spines despite normal spine morphology, thus explaining the synaptic perturbations underlying circuit hyperexcitability.

_Recommended citation: Booker, S.A., Domanski, A.P.F., Dando, O.R. et al. (2019). Altered dendritic spine function and integration in a mouse model of fragile X syndrome. Nature Communications 10(1), 4813. https://doi.org/10.1038/s41467-019-11891-6._
