---
title: "Non-canonical Keap1-independent activation of Nrf2 in astrocytes by mild oxidative stress"
date: 2021-10-02
---

_[Published](https://doi.org/10.1016/j.redox.2021.102158) in Redox Biology_

The transcription factor Nrf2 is a stress-responsive master regulator of antioxidant, detoxification and proteostasis genes. In astrocytes, Nrf2-dependent gene expression drives cell-autonomous cytoprotection and also non-cell-autonomous protection of nearby neurons, and can ameliorate pathology in several acute and chronic neurological disorders associated with oxidative stress. However, the value of astrocytic Nrf2 as a therapeutic target depends in part on whether Nrf2 activation by disease-associated oxidative stress occludes the effect of any Nrf2-activating drug. Nrf2 activation classically involves the inhibition of interactions between Nrf2's Neh2 domain and Keap1, which directs Nrf2 degradation. Keap1 inhibition is mediated by the modification of cysteine residues on Keap1, and can be triggered by electrophilic small molecules such as tBHQ. Here we show that astrocytic Nrf2 activation by oxidative stress involves Keap1-independent non-canonical signaling. Keap1 deficiency elevates basal Nrf2 target gene expression in astrocytes and occludes the effects of tBHQ, oxidative stress still induced strong Nrf2-dependent gene expression in Keap1-deficient astrocytes. Moreover, while tBHQ prevented protein degradation mediated via Nrf2's Neh2 domain, oxidative stress did not, consistent with a Keap1-independent mechanism. Moreover the effects of oxidative stress and tBHQ on Nrf2 target gene expression are additive, not occlusive. Mechanistically, oxidative stress enhances the transactivation potential of Nrf2's Neh5 domain in a manner dependent on its Cys-191 residue. Thus, astrocytic Nrf2 activation by oxidative stress involves Keap1-independent non-canonical signaling, meaning that further Nrf2 activation by Keap1-inhibiting drugs may be a viable therapeutic strategy.

_Recommended citation: Al-Mubarak, B.R., Bell, K.F., Chowdhry, S. et al. (2021). Non-canonical Keap1-independent activation of Nrf2 in astrocytes by mild oxidative stress. Redox Biology 47, 102158. https://doi.org/10.1016/j.redox.2021.102158._
