---
title: "Differential splicing choices made by neurons and astrocytes and their importance when investigating signal-dependent alternative splicing in neural cells"
date: 2023-07-03
---

_[Published](https://doi.org/10.3389/fnmol.2023.1214439) in Frontiers in Molecular Neuroscience_

A variety of proteins can be encoded by a single gene via the differential splicing of exons. In neurons this form of alternative splicing can be controlled by activity-dependent calcium signaling, leading to the properties of proteins being altered, including ion channels, neurotransmitter receptors and synaptic cell adhesion molecules. The pre-synaptic cell adhesion molecule Neurexin 1 (Nrxn1) is alternatively spliced at splice-site 4 (SS4) which governs exon 22 inclusion (SS4+) and consequently postsynaptic NMDA receptor responses. Nrxn1 was reported to be subject to a delayed-onset shift in Nrxn1 SS4 splicing resulting in increased exon 22 inclusion, involving epigenetic mechanisms which, if disrupted, reduce memory stability. Exon inclusion at SS4 represented one of hundreds of exons reported to be subject to a genome-wide shift in fractional exon inclusion following membrane depolarization with high extracellular K+ that was delayed in onset. We report that high K+ does not increase the SS4+/SS4− ratio in cortical neurons, but does induce a delayed-onset NMDA receptor-dependent neuronal death. In mixed neuronal/astrocyte cultures this neuronal death results in an increase in the astrocyte: neuron ratio, and a misleading increase in SS4+/SS4− ratio attributable to astrocytes having a far higher SS4+/SS4− ratio than neurons, rather than any change in the neurons themselves. We reassessed the previously reported genome-wide delayed-onset shift in fractional exon inclusion after high K+ exposure. This revealed that the reported changes correlated strongly with differences in exon inclusion level between astrocytes and neurons, and was accompanied by a strong decrease in the ratio of neuron-specific: astrocyte-specific gene expression. As such, these changes can be explained by the neurotoxic nature of the stimulation paradigm, underlining the importance of NMDA receptor blockade when using high K+ depolarizing stimuli.

_Recommended citation: Baxter PS, Dando O and Hardingham GE (2023) Differential splicing choices made by neurons and astrocytes and their importance when investigating signal-dependent alternative splicing in neural cells. Front. Mol. Neurosci. 16:1214439. doi: 10.3389/fnmol.2023.1214439._
