---
title: "Generation of pure monocultures of human microglia-like cells from induced pluripotent stem cells"
date: 2020-10-14
---

_[Published](https://doi.org/10.1016/j.scr.2020.102046) in Stem Cell Research_

Microglia are resident tissue macrophages of the central nervous system (CNS) that arise from erythromyeloid progenitors during embryonic development. They play essential roles in CNS development, homeostasis and response to disease. Since microglia are difficult to procure from the human brain, several protocols have been developed to generate microglia-like cells from human induced pluripotent stem cells (hiPSCs). However, some concerns remain over the purity and quality of in vitro generated microglia. Here, we describe a new protocol that does not require co-culture with neural cells and yields cultures of 100% P2Y<sub>12</sub><sup>+</sup> 95% TMEM119<sup>+</sup> ramified human microglia-like cells (hiPSC-MG). In the presence of neural precursor cell-conditioned media, hiPSC-MG expressed high levels of human microglia signature genes, including SALL1, CSF1R, P2RY12, TMEM119, TREM2, HEXB and SIGLEC11, as revealed by whole-transcriptome analysis. Stimulation of hiPSC-MG with lipopolysaccharide resulted in downregulation of P2Y<sub>12</sub> expression, induction of IL1B mRNA expression and increase in cell capacitance. HiPSC-MG were phagocytically active and maintained their cell identity after transplantation into murine brain slices and human brain spheroids. Together, our new protocol for the generation of microglia-like cells from human iPSCs will facilitate the study of human microglial function in health and disease.

_Recommended citation: Banerjee, P., Paza, E., Perkins, E.M. et al. (2020). Generation of pure monocultures of human microglia-like cells from induced pluripotent stem cells. Stem Cell Research 49, 102046. https://doi.org/10.1016/j.scr.2020.102046._
