---
title: "Experience-dependent changes in hippocampal spatial activity and hippocampal circuit function are disrupted in a rat model of Fragile X Syndrome"
date: 2022-12-20
---

_[Published](https://doi.org/10.1186/s13229-022-00528-z) in Molecular Autism_

**Background.** Fragile X syndrome (FXS) is a common single gene cause of intellectual disability and autism spectrum disorder. Cognitive inflexibility is one of the hallmarks of FXS with affected individuals showing extreme difficulty adapting to novel or complex situations. To explore the neural correlates of this cognitive inflexibility, we used a rat model of FXS (Fmr1<sup>-/y</sup>).

**Methods.** We recorded from the CA1 in Fmr1<sup>-/y</sup> and WT littermates over six 10-min exploration sessions in a novel environment-three sessions per day (ITI 10 min). Our recordings yielded 288 and 246 putative pyramidal cells from 7 WT and 7 Fmr1<sup>-/y</sup> rats, respectively.

**Results.** On the first day of exploration of a novel environment, the firing rate and spatial tuning of CA1 pyramidal neurons was similar between wild-type (WT) and Fmr1<sup>-/y</sup> rats. However, while CA1 pyramidal neurons from WT rats showed experience-dependent changes in firing and spatial tuning between the first and second day of exposure to the environment, these changes were decreased or absent in CA1 neurons of Fmr1<sup>-/y</sup> rats. These findings were consistent with increased excitability of Fmr1<sup>-/y</sup> CA1 neurons in ex vivo hippocampal slices, which correlated with reduced synaptic inputs from the medial entorhinal cortex. Lastly, activity patterns of CA1 pyramidal neurons were dis-coordinated with respect to hippocampal oscillatory activity in Fmr1<sup>-/y</sup> rats.

**Limitations.** It is still unclear how the observed circuit function abnormalities give rise to behavioural deficits in Fmr1<sup>-/y</sup> rats. Future experiments will focus on this connection as well as the contribution of other neuronal cell types in the hippocampal circuit pathophysiology associated with the loss of FMRP. It would also be interesting to see if hippocampal circuit deficits converge with those seen in other rodent models of intellectual disability.

**Conclusions.** In conclusion, we found that hippocampal place cells from Fmr1<sup>-/y</sup> rats show similar spatial firing properties as those from WT rats but do not show the same experience-dependent increase in spatial specificity or the experience-dependent changes in network coordination. Our findings offer support to a network-level origin of cognitive deficits in FXS.

_Recommended citation: Asiminas, A., Booker, S.A., Dando, O.R. et al. (2022). Experience-dependent changes in hippocampal spatial activity and hippocampal circuit function are disrupted in a rat model of Fragile X Syndrome. Molecular Autism 13(1), 49. https://doi.org/10.1186/s13229-022-00528-z._
