---
title: "Reactive astrocytes acquire neuroprotective as well as deleterious signatures in response to Tau and Aß pathology"
date: 2022-01-10
---

_[Published](https://doi.org/10.1038/s41467-021-27702-w) in Nature Communications_

Alzheimer's disease (AD) alters astrocytes, but the effect of Aß and Tau pathology is poorly understood. TRAP-seq translatome analysis of astrocytes in APP/PS1 ß-amyloidopathy and MAPT<sup>P301S</sup> tauopathy mice revealed that only Aß influenced expression of AD risk genes, but both pathologies precociously induced age-dependent changes, and had distinct but overlapping signatures found in human post-mortem AD astrocytes. Both Aß and Tau pathology induced an astrocyte signature involving repression of bioenergetic and translation machinery, and induction of inflammation pathways plus protein degradation/proteostasis genes, the latter enriched in targets of inflammatory mediator Spi1 and stress-activated cytoprotective Nrf2. Astrocyte-specific Nrf2 expression induced a reactive phenotype which recapitulated elements of this proteostasis signature, reduced Aß deposition and phospho-tau accumulation in their respective models, and rescued brain-wide transcriptional deregulation, cellular pathology, neurodegeneration and behavioural/cognitive deficits. Thus, Aß and Tau induce overlapping astrocyte profiles associated with both deleterious and adaptive-protective signals, the latter of which can slow patho-progression.

_Recommended citation: Jiwaji, Z., Tiwari, S.S., Avilés-Reyes, R.X. et al. (2022). Reactive astrocytes acquire neuroprotective as well as deleterious signatures in response to Tau and Aß pathology. Nature Communications 13(1), 135. https://doi.org/10.1038/s41467-021-27702-w._
