---
title: "Ionotropic GABA and glycine receptor subunit composition in human pluripotent stem cell-derived excitatory cortical neurones"
date: 2014-08-28
---

_[Published](https://doi.org/10.1113/jphysiol.2014.278994) in The Journal of Physiology_

We have assessed, using whole-cell patch-clamp recording and RNA-sequencing (RNA-seq), the properties and composition of GABAA receptors (GABAARs) and strychnine-sensitive glycine receptors (GlyRs) expressed by excitatory cortical neurons derived from human embryonic stem cells (hECNs). The agonists GABA and muscimol gave EC50 values of 278 μm and 182 μm, respectively, and the presence of a GABAAR population displaying low agonist potencies is supported by strong RNA-seq signals for α2 and α3 subunits. GABAAR-mediated currents, evoked by EC50 concentrations of GABA, were blocked by bicuculline and picrotoxin with IC50 values of 2.7 and 5.1 μm, respectively. hECN GABAARs are predominantly γ subunit-containing as assessed by the sensitivity of GABA-evoked currents to diazepam and insensitivity to Zn(2+), together with the weak direct agonist action of gaboxadol; RNA-seq indicated a predominant expression of the γ2 subunit. Potentiation of GABA-evoked currents by propofol and etomidate and the lack of inhibition of currents by salicylidine salycylhydrazide (SCS) indicate expression of the β2 or β3 subunit, with RNA-seq analysis indicating strong expression of β3 in hECN GABAARs. Taken together our data support the notion that hECN GABAARs have an α2/3β3γ2 subunit composition - a composition that also predominates in immature rodent cortex. GlyRs expressed by hECNs were activated by glycine with an EC50 of 167 μm. Glycine-evoked (500 μm) currents were blocked by strychnine (IC50 = 630 nm) and picrotoxin (IC50 = 197 μm), where the latter is suggestive of a population of heteromeric receptors. RNA-seq indicates GlyRs are likely to be composed of α2 and β subunits.

_Recommended citation: James, O.T., Livesey, M.R., Qiu, J. et al. (2014). Ionotropic GABA and glycine receptor subunit composition in human pluripotent stem cell-derived excitatory cortical neurones. The Journal of Physiology 592(19), 4353-4363. https://doi.org/10.1113/jphysiol.2014.278994._
