---
title: "Altered network properties in C9ORF72 repeat expansion cortical neurons are due to synaptic dysfunction"
date: 2021-03-04
---

_[Published](https://doi.org/10.1186/s13024-021-00433-8) in Molecular Neurodegeneration_

**Background.** Physiological disturbances in cortical network excitability and plasticity are established and widespread in amyotrophic lateral sclerosis (ALS) and frontotemporal dementia (FTD) patients, including those harbouring the C9ORF72 repeat expansion (C9ORF72<sup>RE</sup>) mutation - the most common genetic impairment causal to ALS and FTD. Noting that perturbations in cortical function are evidenced pre-symptomatically, and that the cortex is associated with widespread pathology, cortical dysfunction is thought to be an early driver of neurodegenerative disease progression. However, our understanding of how altered network function manifests at the cellular and molecular level is not clear.

**Methods.** To address this we have generated cortical neurons from patient-derived iPSCs harbouring C9ORF72<sup>RE</sup> mutations, as well as from their isogenic expansion-corrected controls. We have established a model of network activity in these neurons using multi-electrode array electrophysiology. We have then mechanistically examined the physiological processes underpinning network dysfunction using a combination of patch-clamp electrophysiology, immunocytochemistry, pharmacology and transcriptomic profiling.

**Results.** We find that C9ORF72<sup>RE</sup> causes elevated network burst activity, associated with enhanced synaptic input, yet lower burst duration, attributable to impaired pre-synaptic vesicle dynamics. We also show that the C9ORF72<sup>RE</sup> is associated with impaired synaptic plasticity. Moreover, RNA-seq analysis revealed dysregulated molecular pathways impacting on synaptic function. All molecular, cellular and network deficits are rescued by CRISPR/Cas9 correction of C9ORF72<sup>RE</sup>. Our study provides a mechanistic view of the early dysregulated processes that underpin cortical network dysfunction in ALS-FTD.

**Conclusion.** These findings suggest synaptic pathophysiology is widespread in ALS-FTD and has an early and fundamental role in driving altered network function that is thought to contribute to neurodegenerative processes in these patients. The overall importance is the identification of previously unidentified defects in pre and postsynaptic compartments affecting synaptic plasticity, synaptic vesicle stores, and network propagation, which directly impact upon cortical function.

_Recommended citation: Perkins, E.M., Burr, K., Banerjee, P. et al. (2021). Altered network properties in C9ORF72 repeat expansion cortical neurons are due to synaptic dysfunction. Molecular Neurodegeneration 16(1), 13. https://doi.org/10.1186/s13024-021-00433-8._
