---
title: "Mitochondrial bioenergetic deficits in C9orf72 amyotrophic lateral sclerosis motor neurons cause dysfunctional axonal homeostasis"
date: 2021-01-04
---

_[Published](https://doi.org/10.1007/s00401-020-02252-5) in Acta Neuropathologica_

Axonal dysfunction is a common phenotype in neurodegenerative disorders, including in amyotrophic lateral sclerosis (ALS), where the key pathological cell-type, the motor neuron (MN), has an axon extending up to a metre long. The maintenance of axonal function is a highly energy-demanding process, raising the question of whether MN cellular energetics is perturbed in ALS, and whether its recovery promotes axonal rescue. To address this, we undertook cellular and molecular interrogation of multiple patient-derived induced pluripotent stem cell lines and patient autopsy samples harbouring the most common ALS causing mutation, C9orf72. Using paired mutant and isogenic expansion-corrected controls, we show that C9orf72 MNs have shorter axons, impaired fast axonal transport of mitochondrial cargo, and altered mitochondrial bioenergetic function. RNAseq revealed reduced gene expression of mitochondrially encoded electron transport chain transcripts, with neuropathological analysis of C9orf72-ALS post-mortem tissue importantly confirming selective dysregulation of the mitochondrially encoded transcripts in ventral horn spinal MNs, but not in corresponding dorsal horn sensory neurons, with findings reflected at the protein level. Mitochondrial DNA copy number was unaltered, both in vitro and in human post-mortem tissue. Genetic manipulation of mitochondrial biogenesis in C9orf72 MNs corrected the bioenergetic deficit and also rescued the axonal length and transport phenotypes. Collectively, our data show that loss of mitochondrial function is a key mediator of axonal dysfunction in C9orf72-ALS, and that boosting MN bioenergetics is sufficient to restore axonal homeostasis, opening new potential therapeutic strategies for ALS that target mitochondrial function.

_Recommended citation: Mehta, A.R., Gregory, J.M., Dando, O. et al. (2021). Mitochondrial bioenergetic deficits in C9orf72 amyotrophic lateral sclerosis motor neurons cause dysfunctional axonal homeostasis. Acta Neuropathologica 141(2), 257-279. https://doi.org/10.1007/s00401-020-02252-5._
