---
title: "Imbalance of flight-freeze responses and their cellular correlates in the Nlgn3^-/y^ rat model of autism"
date: 2022-07-18
---

_[Published](https://doi.org/10.1186/s13229-022-00511-8) in Molecular Autism_

**Background.** Mutations in the postsynaptic transmembrane protein neuroligin-3 are highly correlative with autism spectrum disorders (ASDs) and intellectual disabilities (IDs). Fear learning is well studied in models of these disorders, however differences in fear response behaviours are often overlooked. We aim to examine fear behaviour and its cellular underpinnings in a rat model of ASD/ID lacking Nlgn3.

**Methods.** This study uses a range of behavioural tests to understand differences in fear response behaviour in Nlgn3<sup>-/y</sup> rats. Following this, we examined the physiological underpinnings of this in neurons of the periaqueductal grey (PAG), a midbrain area involved in flight-or-freeze responses. We used whole-cell patch-clamp recordings from ex vivo PAG slices, in addition to in vivo local-field potential recordings and electrical stimulation of the PAG in wildtype and Nlgn3<sup>-/y</sup> rats. We analysed behavioural data with two- and three-way ANOVAS and electrophysiological data with generalised linear mixed modelling (GLMM).

**Results.** We observed that, unlike the wildtype, Nlgn3<sup>-/y</sup> rats are more likely to response with flight rather than freezing in threatening situations. Electrophysiological findings were in agreement with these behavioural outcomes. We found in ex vivo slices from Nlgn3<sup>-/y</sup> rats that neurons in dorsal PAG (dPAG) showed intrinsic hyperexcitability compared to wildtype. Similarly, stimulating dPAG in vivo revealed that lower magnitudes sufficed to evoke flight behaviour in Nlgn3<sup>-/y</sup> than wildtype rats, indicating the functional impact of the increased cellular excitability.

**Limitations.** Our findings do not examine what specific cell type in the PAG is likely responsible for these phenotypes. Furthermore, we have focussed on phenotypes in young adult animals, whilst the human condition associated with NLGN3 mutations appears during the first few years of life.

**Conclusions.** We describe altered fear responses in Nlgn3<sup>-/y</sup> rats and provide evidence that this is the result of a circuit bias that predisposes flight over freeze responses. Additionally, we demonstrate the first link between PAG dysfunction and ASD/ID. This study provides new insight into potential pathophysiologies leading to anxiety disorders and changes to fear responses in individuals with ASD.

_Recommended citation: Anstey, N.J., Kapgal, V., Tiwari, S. et al. (2022). Imbalance of flight-freeze responses and their cellular correlates in the Nlgn3^-/y^ rat model of autism. Molecular Autism 13(1), 34. https://doi.org/10.1186/s13229-022-00511-8._
