---
title: "Sustained correction of associative learning deficits after brief, early treatment in a rat model of Fragile X Syndrome"
date: 2019-05-29
---

_[Published](https://doi.org/10.1126/scitranslmed.aao0498) in Science Translational Medicine_

Fragile X Syndrome (FXS) is one of the most common monogenic forms of autism and intellectual disability. Preclinical studies in animal models have highlighted the potential of pharmaceutical intervention strategies for alleviating the symptoms of FXS. However, whether treatment strategies can be tailored to developmental time windows that define the emergence of particular phenotypes is unknown. Similarly, whether a brief, early intervention can have long-lasting beneficial effects, even after treatment cessation, is also unknown. To address these questions, we first examined the developmental profile for the acquisition of associative learning in a rat model of FXS. Associative memory was tested using a range of behavioral paradigms that rely on an animal's innate tendency to explore novelty. <i>Fmr1</i> knockout (KO) rats showed a developmental delay in their acquisition of object-place recognition and did not demonstrate object-place-context recognition paradigm at any age tested (up to 23 weeks of age). Treatment of <i>Fmr1</i> KO rats with lovastatin between 5 and 9 weeks of age, during the normal developmental period that this associative memory capability is established, prevents the emergence of deficits but has no effect in wild-type animals. Moreover, we observe no regression of cognitive performance in the FXS rats over several months after treatment. This restoration of the normal developmental trajectory of cognitive function is associated with the sustained rescue of both synaptic plasticity and altered protein synthesis. The findings provide proof of concept that the impaired emergence of the cognitive repertoire in neurodevelopmental disorders may be prevented by brief, early pharmacological intervention.

_Recommended citation: Asiminas, A., Jackson, A.D., Louros, S.R. et al. (2019). Sustained correction of associative learning deficits after brief, early treatment in a rat model of Fragile X Syndrome. Science Translational Medicine 11(494), eaao0498. https://doi.org/10.1126/scitranslmed.aao0498._
